name: AndroidBuild

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  androidBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Setup Java SDK
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Android with Gradle
        run: ./gradlew :composeApp:assembleDebug

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ResistorCalculator-KMP.apk
          path: app/build/outputs/apk/debug/app-debug.apk
