name: CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  androidBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Setup Java SDK
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Android with Gradle
        run: ./gradlew :composeApp:assembleDebug

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ResistorCalculator-KMP.apk
          path: composeApp/build/outputs/apk/debug/composeApp-debug.apk

  createTag:
    needs: androidBuild
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.0

      - name: Change to Project Directory
        run: cd composeApp

      - name: Set Git Identity
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create Version Tag
        run: |
          RUN_NUMBER=${{ github.run_number }}
          if [ $((RUN_NUMBER % 2)) -eq 0 ]; then
            VERSION="v${RUN_NUMBER}"
          else
            VERSION="${RUN_NUMBER}"
          fi
          git tag -a $VERSION -m "Version $VERSION"
          git push origin $VERSION

  release:
    needs: createTag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.0

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: composeApp/build/outputs/apk/debug/composeApp-debug.apk
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ github.run_number }}
          title: Release v${{ github.run_number }}
