name: CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  androidBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Setup Java SDK
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Android with Gradle
        run: ./gradlew :composeApp:assembleDebug

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ResistorCalculator-KMP.apk
          path: composeApp/build/outputs/apk/debug/app-debug.apk


#  iosBuild:
#    runs-on: macos-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4.1.0
#
#      - name: Install Dependencies
#        run: |
#          cd ios
#          pod install
#
#      - name: Build iOS
#        run: xcodebuild -workspace iosApp.xcworkspace -scheme iosApp -configuration Release -archivePath build/iosApp.xcarchive archive -quiet
#
#      - name: Export iOS IPA
#        run: xcodebuild -exportArchive -archivePath build/iosApp.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build/ios-ipa -quiet
#
#      - name: Upload iOS IPA
#        uses: actions/upload-artifact@v3.1.3
#        with:
#          name: ios-ipa
#          path: composeApp/build/outputs/apk/debug/ios-ipa